import Head from "next/head"
import { Title, createStyles, rem } from "@mantine/core"
import Search from "@/components/search"
import Services from "@/components/services"
import Articles from "@/components/articles"
import dynamic from "next/dynamic"

const HeaderCarousel = dynamic(() => import("../components/header-carousel"), {
    ssr: false,
})

const Clinics = dynamic(() => import("../components/clinics"), {
    ssr: false,
})

const useStyles = createStyles((theme) => ({
    Title: {
        fontWeight: 500,
        fontSize: rem(20),
    },
}))

export default function Home() {
    const { classes } = useStyles()

    return (
        <>
            <Head>
                <title>DoConnect - The new healthapp</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Title className={classes.Title}>
                    {
                        "No need of panicking at the time of emergency. We've got all the doctors available around you here!"
                    }
                </Title>

                <HeaderCarousel />

                <Search />

                <Services />

                <Clinics />

                <Articles />
            </main>
        </>
    )
}
